name: Package

on:
  workflow_dispatch:
  push:
    branches: [master]
    tags: [v*.*.*]
  pull_request:
    branches: ["**"]

jobs:
  win:
    runs-on: windows-latest
    name: Build Windows x64 Native Lib
    continue-on-error: true
    env:
      CCACHE_BASEDIR: "${{ github.workspace }}"
      CCACHE_DIR: "${{ github.workspace }}\\ccache"
      CCACHE_COMPILERCHECK: content
      CCACHE_COMPRESS: "true"
      CCACHE_COMPRESSLEVEL: 9
      CCACHE_MAXSIZE: 200M
      ccache_version: "4.5"
      VCPKG_DEFAULT_BINARY_CACHE: "${{ github.workspace }}\\vcpkg\\"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Download ccache
        shell: cmake -P {0}
        run: |
          set(ccache_url "https://github.com/cristianadam/ccache/releases/download/v${{ env.ccache_version }}/${{ runner.os }}.tar.xz")
          file(DOWNLOAD "${ccache_url}" ./ccache.tar.xz SHOW_PROGRESS)
          execute_process(COMMAND ${CMAKE_COMMAND} -E tar xvf ./ccache.tar.xz)

      - name: Generate ccache_vars for ccache based on machine
        shell: cmake -P {0}
        id: ccache_vars
        run: |-
          string(TIMESTAMP current_date "%Y-%m-%d-%H;%M;%S" UTC)
          message("::set-output name=timestamp::${current_date}")
          message("::set-output name=hash::${{ env.ccache_compilercheck }}")

      - name: Cache-op for build-cache through ccache
        uses: actions/cache@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-windows-x64-${{ steps.ccache_vars.outputs.hash }}-${{ github.ref }}-${{ steps.ccache_vars.outputs.timestamp }}
          restore-keys: |-
            ccache-windows-x64-${{ steps.ccache_vars.outputs.hash }}-${{ github.ref }}
            ccache-windows-x64

      - name: Cache-op for build-cache through vcpkg
        uses: actions/cache@v4
        with:
          path: ${{ env.VCPKG_DEFAULT_BINARY_CACHE }}
          key: vcpkg-windows-x64-${{ steps.ccache_vars.outputs.hash }}-${{ github.ref }}-${{ steps.ccache_vars.outputs.timestamp }}
          restore-keys: |-
            vcpkg-windows-x64-${{ steps.ccache_vars.outputs.hash }}-${{ github.ref }}
            vcpkg-windows-x64

      - name: ccache prolog
        run: |-
          cmake -E make_directory ${{github.workspace}}\vcpkg
          cmake -E make_directory ${{github.workspace}}\build

      - name: Configure
        working-directory: ${{github.workspace}}/build
        run: |
          cmake .. -DBUILD_ARCH=corei7-avx -DCMAKE_BUILD_TYPE=Release -DUSE_STATIC_LIBS=ON  -DVCPKG_TARGET_TRIPLET='x64-windows-static' `
                -DCMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake"  `
                -DCMAKE_CXX_COMPILER_LAUNCHER=${{github.workspace}}\ccache.exe `
                -DCMAKE_C_COMPILER_LAUNCHER=${{github.workspace}}\ccache.exe
        shell: powershell

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build . --config Release -j3 --target bergamot_translator_dynamic
        shell: powershell

      - name: Install
        working-directory: ${{github.workspace}}/build
        run: cmake --install . --prefix "../libs/runtimes/win-x64/native" --component bergamot_translator_dynamic
        shell: powershell

      - uses: actions/upload-artifact@v4
        with:
          name: libs-win-x64
          path: libs/*

  win-arm64:
    runs-on: windows-latest
    name: Build Windows ARM64 Native Lib
    continue-on-error: true
    env:
      CCACHE_BASEDIR: "${{ github.workspace }}"
      CCACHE_DIR: "${{ github.workspace }}\\ccache"
      CCACHE_COMPILERCHECK: content
      CCACHE_COMPRESS: "true"
      CCACHE_COMPRESSLEVEL: 9
      CCACHE_MAXSIZE: 200M
      ccache_version: "4.5"
      VCPKG_DEFAULT_BINARY_CACHE: "${{ github.workspace }}\\vcpkg\\"
      VCPKG_TARGET_TRIPLET: arm64-windows-static
      VCPKG_HOST_TRIPLET: x64-windows
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Download ccache
        shell: cmake -P {0}
        run: |
          set(ccache_url "https://github.com/cristianadam/ccache/releases/download/v${{ env.ccache_version }}/${{ runner.os }}.tar.xz")
          file(DOWNLOAD "${ccache_url}" ./ccache.tar.xz SHOW_PROGRESS)
          execute_process(COMMAND ${CMAKE_COMMAND} -E tar xvf ./ccache.tar.xz)

      - name: Generate ccache_vars for ccache based on machine
        shell: cmake -P {0}
        id: ccache_vars
        run: |-
          string(TIMESTAMP current_date "%Y-%m-%d-%H;%M;%S" UTC)
          message("::set-output name=timestamp::${current_date}")
          message("::set-output name=hash::${{ env.ccache_compilercheck }}")

      - name: Cache-op for build-cache through ccache
        uses: actions/cache@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-windows-arm64-${{ steps.ccache_vars.outputs.hash }}-${{ github.ref }}-${{ steps.ccache_vars.outputs.timestamp }}
          restore-keys: |-
            ccache-windows-arm64-${{ steps.ccache_vars.outputs.hash }}-${{ github.ref }}
            ccache-windows-arm64

      - name: Cache-op for build-cache through vcpkg
        uses: actions/cache@v4
        with:
          path: ${{ env.VCPKG_DEFAULT_BINARY_CACHE }}
          key: vcpkg-windows-arm64-${{ steps.ccache_vars.outputs.hash }}-${{ github.ref }}-${{ steps.ccache_vars.outputs.timestamp }}
          restore-keys: |-
            vcpkg-windows-arm64-${{ steps.ccache_vars.outputs.hash }}-${{ github.ref }}
            vcpkg-windows-arm64

      - name: ccache prolog
        run: |-
          cmake -E make_directory ${{github.workspace}}\vcpkg
          cmake -E make_directory ${{github.workspace}}\build

      - name: Configure
        working-directory: ${{github.workspace}}/build
        run: |
          cmake .. -G "Visual Studio 17 2022" -A ARM64 -Thost=x64 -DCMAKE_BUILD_TYPE=Release -DUSE_STATIC_LIBS=ON -DUSE_MKL=OFF -DVCPKG_TARGET_TRIPLET='arm64-windows-static' `
                -DCMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake"  `
                -DCMAKE_CXX_COMPILER_LAUNCHER=${{github.workspace}}\ccache.exe `
                -DCMAKE_C_COMPILER_LAUNCHER=${{github.workspace}}\ccache.exe
        shell: powershell

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build . --config Release -j3 --target bergamot_translator_dynamic
        shell: powershell

      - name: Install
        working-directory: ${{github.workspace}}/build
        run: cmake --install . --prefix "../libs/runtimes/win-arm64/native" --component bergamot_translator_dynamic
        shell: powershell

      - uses: actions/upload-artifact@v4
        with:
          name: libs-win-arm64
          path: libs/*

  linux:
    runs-on: ubuntu-latest
    name: Build Linux x64 Native Lib
    continue-on-error: true
    env:
      ccache_basedir: ${{ github.workspace }}
      ccache_dir: "${{ github.workspace }}/.ccache"
      ccache_compilercheck: content
      ccache_compress: 'true'
      ccache_compresslevel: 9
      ccache_maxsize: 200M
      ccache_cmake: -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER_LAUNCHER=ccache
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Dependencies
        run: |-
          sudo apt-get update
          sudo apt-get install -y libprotobuf-dev protobuf-compiler libboost-all-dev ccache libunwind-dev libgoogle-perftools-dev
      - name: Install MKL
        run: |-
          wget -qO- "https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB" | sudo apt-key add -
          sudo sh -c "echo deb https://apt.repos.intel.com/mkl all main > /etc/apt/sources.list.d/intel-mkl.list"
          sudo apt-get update -o Dir::Etc::sourcelist="/etc/apt/sources.list.d/intel-mkl.list"
          sudo apt-get install -y --no-install-recommends intel-mkl-64bit-2020.0-088
      - name: Generate ccache_vars for ccache based on machine
        shell: bash
        id: ccache_vars
        run: |-
          echo "hash=$(echo ${{ env.ccache_compilercheck }})" >> $GITHUB_OUTPUT
          echo "timestamp=$(date '+%Y-%m-%dT%H.%M.%S')" >> $GITHUB_OUTPUT
      - name: Cache-op for build-cache through ccache
        uses: actions/cache@v4
        with:
          path: ${{ env.ccache_dir }}
          key: ccache-linux-x64-${{ steps.ccache_vars.outputs.hash }}-${{ github.ref }}-${{ steps.ccache_vars.outputs.timestamp }}
          restore-keys: |-
            ccache-linux-x64-${{ steps.ccache_vars.outputs.hash }}-${{ github.ref }}
            ccache-linux-x64
      - name: ccache environment setup
        run: |-
          echo "CCACHE_COMPILER_CHECK=${{ env.ccache_compilercheck }}" >> $GITHUB_ENV
          echo "CCACHE_BASEDIR=${{ env.ccache_basedir }}" >> $GITHUB_ENV
          echo "CCACHE_COMPRESS=${{ env.ccache_compress }}" >> $GITHUB_ENV
          echo "CCACHE_COMPRESSLEVEL=${{ env.ccache_compresslevel }}" >> $GITHUB_ENV
          echo "CCACHE_DIR=${{ env.ccache_dir }}" >> $GITHUB_ENV
          echo "CCACHE_MAXSIZE=${{ env.ccache_maxsize }}" >> $GITHUB_ENV
      - name: ccache prolog
        run: |-
          ccache -s
          ccache -z
      - name: cmake
        run: |-
          mkdir -p build
          cd build
          cmake -L .. ${{ env.ccache_cmake }} -DCMAKE_BUILD_TYPE=Release -DUSE_STATIC_LIBS=ON
      - name: Build from source
        working-directory: build
        run: cmake --build . --config Release -j3 --target bergamot_translator_dynamic
      - name: Install
        working-directory: build
        run: cmake --install . --prefix "../libs/runtimes/linux-x64/native" --component bergamot_translator_dynamic
      - uses: actions/upload-artifact@v4
        with:
          name: libs-linux-x64
          path: libs/*

  linux-arm64:
    runs-on: ubuntu-latest
    name: Build Linux ARM64 Native Lib
    continue-on-error: true
    env:
      ccache_basedir: ${{ github.workspace }}
      ccache_dir: "${{ github.workspace }}/.ccache"
      ccache_compilercheck: content
      ccache_compress: 'true'
      ccache_compresslevel: 9
      ccache_maxsize: 200M
      ccache_cmake: -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER_LAUNCHER=ccache
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: Setup Multi-Arch APT Repositories
        run: |
          sudo dpkg --add-architecture arm64
          sudo sed -i 's/azure.archive.ubuntu.com/archive.ubuntu.com/g' /etc/apt/sources.list
          sudo cp /etc/apt/sources.list /etc/apt/sources.list.d/arm64.list
          sudo sed -i -e 's/http:\/\/archive.ubuntu.com\/ubuntu\//http:\/\/ports.ubuntu.com\/ubuntu-ports\//g' \
                      -e 's/http:\/\/security.ubuntu.com\/ubuntu\//http:\/\/ports.ubuntu.com\/ubuntu-ports\//g' \
                      /etc/apt/sources.list.d/arm64.list
          sudo sed -i 's/deb http/deb [arch=amd64,i386] http/g' /etc/apt/sources.list
          sudo sed -i 's/deb http/deb [arch=arm64] http/g' /etc/apt/sources.list.d/arm64.list
          sudo apt-get update

      - name: Install Cross-Compile Dependencies
        run: |
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu ccache \
                                 protobuf-compiler libprotobuf-dev:arm64 \
                                 libboost-all-dev:arm64 libunwind-dev:arm64 \
                                 libgoogle-perftools-dev:arm64 libopenblas-dev:arm64

      - name: Generate ccache_vars
        shell: bash
        id: ccache_vars
        run: |-
          echo "hash=$(echo ${{ env.ccache_compilercheck }})" >> $GITHUB_OUTPUT
          echo "timestamp=$(date '+%Y-%m-%dT%H.%M.%S')" >> $GITHUB_OUTPUT
          
      - name: Cache-op for build-cache through ccache
        uses: actions/cache@v4
        with:
          path: ${{ env.ccache_dir }}
          key: ccache-linux-arm64-${{ steps.ccache_vars.outputs.hash }}-${{ github.ref }}-${{ steps.ccache_vars.outputs.timestamp }}
          restore-keys: |-
            ccache-linux-arm64-${{ steps.ccache_vars.outputs.hash }}-${{ github.ref }}
            ccache-linux-arm64
            
      - name: ccache environment setup
        run: |-
          echo "CCACHE_COMPILER_CHECK=${{ env.ccache_compilercheck }}" >> $GITHUB_ENV
          echo "CCACHE_BASEDIR=${{ env.ccache_basedir }}" >> $GITHUB_ENV
          echo "CCACHE_COMPRESS=${{ env.ccache_compress }}" >> $GITHUB_ENV
          echo "CCACHE_COMPRESSLEVEL=${{ env.ccache_compresslevel }}" >> $GITHUB_ENV
          echo "CCACHE_DIR=${{ env.ccache_dir }}" >> $GITHUB_ENV
          echo "CCACHE_MAXSIZE=${{ env.ccache_maxsize }}" >> $GITHUB_ENV
          
      - name: ccache prolog
        run: |-
          ccache -s
          ccache -z
          
      - name: cmake
        run: |-
          mkdir -p build
          cd build
          cmake -L .. ${{ env.ccache_cmake }} \
            -DCMAKE_SYSTEM_NAME=Linux \
            -DCMAKE_SYSTEM_PROCESSOR=aarch64 \
            -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc \
            -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++ \
            -DProtobuf_PROTOC_EXECUTABLE=/usr/bin/protoc \
            -DCMAKE_BUILD_TYPE=Release \
            -DUSE_MKL=OFF \
            -DUSE_STATIC_LIBS=ON
            
      - name: Build from source
        working-directory: build
        run: cmake --build . --config Release -j3 --target bergamot_translator_dynamic
        
      - name: Install
        working-directory: build
        run: cmake --install . --prefix "../libs/runtimes/linux-arm64/native" --component bergamot_translator_dynamic
        
      - uses: actions/upload-artifact@v4
        with:
          name: libs-linux-arm64
          path: libs/*

  dotnet:
    runs-on: ubuntu-latest
    name: Build .NET Lib
    needs:
      - win
      - win-arm64
      - linux
      - linux-arm64
    if: ${{ !cancelled() }}
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - uses: gittools/actions/gitversion/setup@v3.1.11
        with:
          versionSpec: "5.x"
      - id: gitversion
        uses: gittools/actions/gitversion/execute@v3.1.11

      - name: Download Windows x64 Artifacts
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: libs-win-x64
          path: BergamotTranslatorSharp

      - name: Download Windows ARM64 Artifacts
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: libs-win-arm64
          path: BergamotTranslatorSharp

      - name: Download Linux x64 Artifacts
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: libs-linux-x64
          path: BergamotTranslatorSharp

      - name: Download Linux ARM64 Artifacts
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: libs-linux-arm64
          path: BergamotTranslatorSharp

      - name: Run .NET Pack
        run: |
          dotnet pack BergamotTranslatorSharp -c Release -o pack \
            -p:Version=${{ steps.gitversion.outputs.fullSemVer }} \
            -p:AssemblyVersion=${{ steps.gitversion.outputs.assemblySemVer }} \
            -p:FileVersion=${{ steps.gitversion.outputs.assemblySemFileVer }} \
            -p:InformationalVersion=${{ steps.gitversion.outputs.informationalVersion }}
      - uses: actions/upload-artifact@v4
        with:
          name: nupkg
          path: pack/*
      - if: ${{ success() && startsWith(github.ref, 'refs/tags/') }}
        run: dotnet nuget push pack/*.nupkg -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate
      - if: ${{ success() && startsWith(github.ref, 'refs/tags/') }}
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          draft: false
          prerelease: false
